CREATE TABLE salas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE,
    capacidade INTEGER NOT NULL CHECK (capacidade >= 1),
    localizacao VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ATIVA', 'INATIVA'))
);

CREATE TABLE reservas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sala_id BIGINT NOT NULL,
    nome_solicitante VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    data_reserva DATE NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fim TIME NOT NULL,
    finalidade VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ATIVA', 'CANCELADA')),
    CONSTRAINT fk_reservas_salas FOREIGN KEY (sala_id) REFERENCES salas (id)
);

INSERT INTO salas (nome, capacidade, localizacao, status) VALUES
    ('Sala Reuniao A', 10, 'Bloco 1 - 2 andar', 'ATIVA'),
    ('Sala Treinamento', 25, 'Bloco 2 - Terreo', 'ATIVA'),
    ('Sala Diretoria', 8, 'Bloco Administrativo', 'INATIVA');

INSERT INTO reservas (
    sala_id,
    nome_solicitante,
    email,
    data_reserva,
    hora_inicio,
    hora_fim,
    finalidade,
    status
) VALUES
    (
        1,
        'Ana Oliveira',
        'ana.oliveira@example.com',
        DATE '2026-06-17',
        TIME '09:00:00',
        TIME '10:00:00',
        'Reuniao de planejamento',
        'ATIVA'
    ),
    (
        2,
        'Carlos Souza',
        'carlos.souza@example.com',
        DATE '2026-06-18',
        TIME '14:00:00',
        TIME '16:00:00',
        'Treinamento da equipe',
        'ATIVA'
    );
